name: "system:package:version:create [push:master]"

on:
  push:
    branches:
      - master
    paths:
      - "force-app/**"

jobs:
  create-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: "Checkout source code"
        uses: actions/checkout@v2

      - name: "Install Salesforce CLI"
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      - name: "Populate auth file with DEVHUB_AUTH_URL secret"
        shell: bash
        run: "echo ${{ secrets.DEVHUB_AUTH_URL}} > ./DEVHUB_AUTH_URL.txt"

      - name: "Authenticate Dev Hub"
        run: "sfdx auth:sfdxurl:store -f ./DEVHUB_AUTH_URL.txt -a devhub -d"

      - name: "Create new package version"
        run: 'sfdx force:package:version:create --package "${{ secrets.PACKAGE_NAME }}" --codecoverage --installationkeybypass --definitionfile config/project-scratch-def.json --wait 10'

      - name: "Commit Changes"
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email activation@hundw.com
          git add sfdx-project.json
          git commit -m "Package Version created"
          git push
