# Unique name for this workflow
name: Create Package Version

# Definition when the workflow should run
on:
  release:
    types: [published]
    branches:
      - master

# Jobs to be executed
jobs:
  create-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1

      # Checkout the code
      - name: "Checkout source code"
        uses: actions/checkout@v2

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      # Store secret for dev hub
      - name: "Populate auth file with DEVHUB_AUTH_URL secret"
        shell: bash
        run: "echo ${{ secrets.DEVHUB_AUTH_URL}} > ./DEVHUB_AUTH_URL.txt"

      # Authenticate dev hub
      - name: "Authenticate Dev Hub"
        run: "sfdx force:auth:sfdxurl:store -f ./DEVHUB_AUTH_URL.txt -a devhub -d"

      # Promote Package Version
      - name: "Promote Package Version"
        run: |
          latestVersion=$(sfdx force:package:version:list -p ${{ env.GITHUB_REPOSITORY_NAME }} -o CreatedDate --concise | tail -1 | awk '{print $3}')
          "sfdx force:package:version:promote --package $latestVersion
