# Copyright 2021 Oliver Preuschl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "user:scratch-org:dependencies:install [feature]"

on:
  workflow_dispatch:
    inputs:
      pushSource:
        type: boolean
        description: Push Source after installation
        required: false

jobs:
  InstallDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        if: env.GITHUB_REF_NAME != 'master'
        uses: actions/checkout@v2

      - name: "Install Salesforce CLI"
        if: env.GITHUB_REF_NAME != 'master'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      - name: "Populate auth file with DEVHUB_AUTH_URL secret"
        if: env.GITHUB_REF_NAME != 'master'
        shell: bash
        run: "echo ${{ secrets.DEVHUB_AUTH_URL}} > ./DEVHUB_AUTH_URL.txt"

      - name: "Authenticate Dev Hub"
        if: env.GITHUB_REF_NAME != 'master'
        run: "sfdx auth:sfdxurl:store -f ./DEVHUB_AUTH_URL.txt -a devhub -d"

      - name: "Get Branch Name"
        if: env.GITHUB_REF_NAME != 'master'
        id: get_branch_name
        run: |
          branchname='${{ env.GITHUB_REF_NAME }}'
          branchname="${branchname//[^0-9a-zA-Z_]/_}"
          echo "::set-output name=branch_name::$branchname"

      - name: "Get Scratch-Org-Auth-URL"
        if: env.GITHUB_REF_NAME != 'master'
        id: get_scratch_org_auth_url
        run: |
          chmod +x ./.github/scripts/getScratchOrgAuthUrl.js
          authurl=$(node ./.github/scripts/getScratchOrgAuthUrl.js "${{ steps.get_branch_name.outputs.branch_name }}")
          echo "::set-output name=auth_url::$authurl"

      - name: "Populate auth file with SCRATCH_ORG_AUTH_URL secret"
        if: env.GITHUB_REF_NAME != 'master'
        run: |
          authurl=${{ steps.get_scratch_org_auth_url.outputs.auth_url }}
          echo $authurl > ./SCRATCH_ORG_AUTH_URL.txt

      - name: "Authenticate Scratch Org"
        if: env.GITHUB_REF_NAME != 'master'
        run: "sfdx auth:sfdxurl:store -f ./SCRATCH_ORG_AUTH_URL.txt -a scratchorg -s"

      - name: "Deploy Org-Dependencies to ScratchOrg"
        if: env.GITHUB_REF_NAME != 'master'
        run: "sfdx force:source:deploy -p 0-force-org-dependency"

      - name: "Install SFDX-Project-Dependencies"
        if: ${{ env.GITHUB_REF_NAME != 'master' && github.event.inputs.pushSource == 'true' }}
        run: |
          chmod +x ./.github/scripts/installPackageDependencies.js
          node ./.github/scripts/installPackageDependencies.js scratchorg

      - name: "Push Source to ScratchOrg"
        if: env.GITHUB_REF_NAME != 'master'
        run: "sfdx force:source:push --forceoverwrite --ignorewarnings"
