# Unique name for this workflow
name: User - 2 - Create Package

# Definition when the workflow should run
on:
  workflow_dispatch

# Jobs to be executed
jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1

      # Checkout the code
      - name: "Checkout source code"
        if: env.GITHUB_REF_NAME == 'master'
        uses: actions/checkout@v2

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        if: env.GITHUB_REF_NAME == 'master'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      # Store secret for dev hub
      - name: "Populate auth file with DEVHUB_AUTH_URL secret"
        if: env.GITHUB_REF_NAME == 'master'
        shell: bash
        run: "echo ${{ secrets.DEVHUB_AUTH_URL}} > ./DEVHUB_AUTH_URL.txt"

      # Authenticate dev hub
      - name: "Authenticate Dev Hub"
        if: env.GITHUB_REF_NAME == 'master'
        run: "sfdx auth:sfdxurl:store -f ./DEVHUB_AUTH_URL.txt -a devhub -d"

      # Create Package Version
      - name: "Create new package version"
        if: env.GITHUB_REF_NAME == 'master'
        run: "sfdx force:package:create --name ${{ env.GITHUB_REPOSITORY_NAME }} --path force-app --packagetype Unlocked"

      # Commit Changes
      - name: "Commit Changes"
        if: env.GITHUB_REF_NAME == 'master'
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email activation@hundw.com
          git add sfdx-project.json
          git commit -m "Package created"
          git push
