# Copyright 2021 Oliver Preuschl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "user:scratch-org:create [feature]"

on: workflow_dispatch

jobs:
  CreateScratchOrg:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch_name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Extract repository name
        id: extract_repository_name
        shell: bash
        run: echo "##[set-output name=repository;]$(echo ${GITHUB_REPOSITORY/\//-})"

      - name: "Checkout source code"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        uses: actions/checkout@v2

      - name: "Install Salesforce CLI"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        run: |
          wget -nv https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-x64.tar.xz -C sfdx-cli --strip-components 1
          export PATH=./sfdx-cli/bin:$PATH
          echo "./sfdx-cli/bin" >> $GITHUB_PATH
          sfdx update

      - name: "Populate auth file with DEVHUB_AUTH_URL secret"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        shell: bash
        run: "echo ${{ secrets.DEVHUB_AUTH_URL}} > ./DEVHUB_AUTH_URL.txt"

      - name: "Authenticate Dev Hub"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        run: "sfdx auth:sfdxurl:store -f ./DEVHUB_AUTH_URL.txt -a devhub -d"

      - name: "Get ScratchOrg Name"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        id: get_scratch_org_name
        run: |
          scratchorgname='${{ steps.extract_repository_name.outputs.branch }}_master'
          echo "::set-output name=scratch_org_name::$scratchorgname"

      - name: "Create scratch org"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        run: 'sfdx force:org:create --definitionfile config/project-scratch-def.json --setalias="${{ steps.get_scratch_org_name.outputs.scratch_org_name }}" --setdefaultusername --durationdays 30'

      - name: "Get Branch Name"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        id: get_branch_name
        run: |
          branchname='${{ steps.extract_branch_name.outputs.branch }}'
          branchname="${branchname//[^0-9a-zA-Z_]/_}"
          echo "::set-output name=branch_name::$branchname"

      - name: "Save Scratch-Orgs-JSON"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        id: save_scratch-orgs-json
        run: |
          chmod +x ./.github/scripts/buildScratchOrgFile.js
          json=$(node ./.github/scripts/buildScratchOrgFile.js "${{ steps.get_branch_name.outputs.branch_name }}" "${{ steps.get_scratch_org_name.outputs.scratch_org_name }}")
          echo $json > ./sfdx-scratch-orgs.json

      - name: "Build README"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        run: |
          chmod +x ./.github/scripts/buildReadme.js
          node ./.github/scripts/buildReadme.js

      - name: "Save SfdxScratchOrgAuthUrl"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        id: save_sfdx_auth_url
        run: |
          chmod +x ./.github/scripts/buildSfdxAuthUrlFile.js
          authUrl=$(node ./.github/scripts/buildSfdxAuthUrlFile.js "${{ steps.get_branch_name.outputs.branch_name }}" "${{ steps.get_scratch_org_name.outputs.scratch_org_name }}")
          echo $authUrl > ./config/scratch-org-auth-url.txt

      - name: "Commit Changes"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email activation@hundw.com
          git add sfdx-scratch-orgs.json config/scratch-org-auth-url.txt README.md
          git commit -m "Scratch Org created"
          git push

      - name: "Display Scratch Org Login Link"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        run: 'sfdx force:org:open -u="${{ steps.get_scratch_org_name.outputs.scratch_org_name }}"'

      - name: "Deploy Org-Dependencies to ScratchOrg"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        continue-on-error: true
        run: "sfdx force:source:deploy -p 0-force-org-dependency --ignorewarnings --ignoreerrors"

      - name: "Install SFDX-Project-Dependencies"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        run: |
          chmod +x ./.github/scripts/installPackageDependencies.js
          node ./.github/scripts/installPackageDependencies.js "${{ steps.get_scratch_org_name.outputs.scratch_org_name }}"

      - name: "Push Source to ScratchOrg"
        if: ${{ steps.extract_branch_name.outputs.branch != 'master' }}
        run: "sfdx force:source:push"
