name: "user:package:unlocked:create [master]"

on: workflow_dispatch

jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: "Checkout source code"
        if: env.GITHUB_REF_NAME == 'master'
        uses: actions/checkout@v2

      - name: "Install Salesforce CLI"
        if: env.GITHUB_REF_NAME == 'master'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      - name: "Populate auth file with DEVHUB_AUTH_URL secret"
        if: env.GITHUB_REF_NAME == 'master'
        shell: bash
        run: "echo ${{ secrets.DEVHUB_AUTH_URL}} > ./DEVHUB_AUTH_URL.txt"

      - name: "Authenticate Dev Hub"
        if: env.GITHUB_REF_NAME == 'master'
        run: "sfdx auth:sfdxurl:store -f ./DEVHUB_AUTH_URL.txt -a devhub -d"

      - name: "Get Package Name"
        id: get_package_name
        run: |
          chmod +x ./.github/scripts/getPackageAttribute.js
          name='$(node ./.github/scripts/getPackageAttribute.js name)'
          echo "::set-output name=package_name::$name"

      - name: "Create new package"
        if: env.GITHUB_REF_NAME == 'master'
        run: 'sfdx force:package:create --name "${{ steps.get_package_name.outputs.package_name }}" --path 2-force-app --packagetype Unlocked'

      - name: "Commit Changes"
        if: env.GITHUB_REF_NAME == 'master'
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email activation@hundw.com
          git add sfdx-project.json
          git commit -m "Package created"
          git push
