name: "user:package:version:promote [master]"

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: "Version Name"
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: "Checkout code"
        if: env.GITHUB_REF_NAME == 'master'
        uses: actions/checkout@v2

      - name: "Install Salesforce CLI"
        if: env.GITHUB_REF_NAME == 'master'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      - name: "Populate auth file with DEVHUB_AUTH_URL secret"
        if: env.GITHUB_REF_NAME == 'master'
        shell: bash
        run: "echo ${{ secrets.DEVHUB_AUTH_URL}} > ./DEVHUB_AUTH_URL.txt"

      - name: "Authenticate Dev Hub"
        if: env.GITHUB_REF_NAME == 'master'
        run: "sfdx auth:sfdxurl:store -f ./DEVHUB_AUTH_URL.txt -a devhub -d"

      - name: "Promote Package Version"
        if: env.GITHUB_REF_NAME == 'master'
        id: promote_package_version
        run: |
          latestVersion=$(sfdx force:package:version:list -p "${{ secrets.PACKAGE_NAME }}" -o CreatedDate --concise | tail -1 | awk '{print $3}')
          sfdx force:package:version:promote --package $latestVersion --noprompt
          echo "::set-output name=latest_package_version_id::$latestVersion"

      - name: "Create Release"
        if: env.GITHUB_REF_NAME == 'master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ github.event.inputs.versionName }}"
          release_name: "Release ${{ github.event.inputs.versionName }}"
          body: |
            /packaging/installPackage.apexp?p0=${{ steps.promote_package_version.outputs.latest_package_version_id }}
          draft: false
          prerelease: false
