# Copyright 2021 Oliver Preuschl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "user:readme:build"

on:
  workflow_dispatch:

jobs:
  build-readme:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2

      - name: "Install npm dependencies"
        run: npm ci

      - name: "Install Salesforce CLI"
        run: |
          wget -nv https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-x64.tar.xz -C sfdx-cli --strip-components 1
          export PATH=./sfdx-cli/bin:$PATH
          echo "./sfdx-cli/bin" >> $GITHUB_PATH
          sfdx update

      - name: "Populate auth file with DEVHUB_AUTH_URL secret"
        shell: bash
        run: "echo ${{ secrets.DEVHUB_AUTH_URL}} > ./DEVHUB_AUTH_URL.txt"

      - name: "Authenticate Dev Hub"
        run: "sfdx auth:sfdxurl:store -f ./DEVHUB_AUTH_URL.txt -a devhub -d"

      - name: "Save Package-Versions-JSON"
        id: save_package_versions
        run: |
          chmod +x ./.github/scripts/getPackageVersions.js
          node ./.github/scripts/getPackageVersions.js > ./sfdx-package-versions.json

      - name: "Build README"
        run: |
          chmod +x ./.github/scripts/buildReadme.js
          node ./.github/scripts/buildReadme.js

      - name: "Commit Changes"
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email activation@hundw.com
          git add README.md
          git commit -m "Auto-Updated README.md"
          git push
