# Copyright 2021 Oliver Preuschl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "user:scratch-org:create [feature]"

on: workflow_dispatch

jobs:
  CreateScratchOrg:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: "Checkout source code"
        if: env.GITHUB_REF_NAME != 'master'
        uses: actions/checkout@v2

      - name: "Install Salesforce CLI"
        if: env.GITHUB_REF_NAME != 'master'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      - name: "Populate auth file with DEVHUB_AUTH_URL secret"
        if: env.GITHUB_REF_NAME != 'master'
        shell: bash
        run: "echo ${{ secrets.DEVHUB_AUTH_URL}} > ./DEVHUB_AUTH_URL.txt"

      - name: "Authenticate Dev Hub"
        if: env.GITHUB_REF_NAME != 'master'
        run: "sfdx auth:sfdxurl:store -f ./DEVHUB_AUTH_URL.txt -a devhub -d"

      - name: "Get ScratchOrg Name"
        if: env.GITHUB_REF_NAME != 'master'
        id: get_scratch_org_name
        run: |
          scratchorgname='${{ env.GITHUB_REPOSITORY_NAME }}_master'
          echo "::set-output name=scratch_org_name::$scratchorgname"

      - name: "Create scratch org"
        if: env.GITHUB_REF_NAME != 'master'
        run: 'sfdx force:org:create --definitionfile config/project-scratch-def.json --setalias="${{ steps.get_scratch_org_name.outputs.scratch_org_name }}" --setdefaultusername --durationdays 30'

      - name: "Get Branch Name"
        if: env.GITHUB_REF_NAME != 'master'
        id: get_branch_name
        run: |
          branchname='${{ env.GITHUB_REF_NAME }}'
          branchname="${branchname//[^0-9a-zA-Z_]/_}"
          echo "::set-output name=branch_name::$branchname"

      - name: "Save Scratch-Orgs-JSON"
        if: env.GITHUB_REF_NAME != 'master'
        id: save_scratch-orgs-json
        run: |
          chmod +x ./.github/scripts/buildScratchOrgFile.js
          json=$(node ./.github/scripts/buildScratchOrgFile.js "${{ steps.get_branch_name.outputs.branch_name }}" "${{ steps.get_scratch_org_name.outputs.scratch_org_name }}")
          echo $json > ./sfdx-scratch-orgs.json

      - name: "Build README"
        if: env.GITHUB_REF_NAME != 'master'
        run: |
          chmod +x ./.github/scripts/buildReadme.js
          node ./.github/scripts/buildReadme.js

      - name: "Commit Changes"
        if: env.GITHUB_REF_NAME != 'master'
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email activation@hundw.com
          git add sfdx-scratch-orgs.json README.md
          git commit -m "Scratch Org created"
          git push

      - name: "Display Scratch Org Login Link"
        if: env.GITHUB_REF_NAME != 'master'
        run: 'sfdx force:org:open -u="${{ steps.get_scratch_org_name.outputs.scratch_org_name }}"'

      - name: "Install SFDX-Project-Dependencies"
        if: env.GITHUB_REF_NAME != 'master'
        run: |
          chmod +x ./.github/scripts/installPackageDependencies.js
          node ./.github/scripts/installPackageDependencies.js "${{ steps.get_scratch_org_name.outputs.scratch_org_name }}"

      - name: "Push Source to ScratchOrg"
        if: env.GITHUB_REF_NAME != 'master'
        run: "sfdx force:source:push"
